---
- block: # Install Docker
  - name: Check if docker-engine is installed
    command: dpkg-query -l docker-engine
    failed_when: false
    register: install_docker_package_check

  #NOTE Change to use http apt so it can be cached with apt-cacher-ng
  - name: Install Docker if not installed
    shell: curl -sSL https://get.docker.com/ | sed 's#https://apt\.dockerproject\.org#http://apt.dockerproject.org#' | sh
    when: install_docker_package_check.rc != 0
    register: install_docker
    when: ansible_os_family == 'Debian'

  - block:
    - name: Add Docker GPG key.
      rpm_key:
        key: "{{ install_docker_yum_gpg_key }}"
        state: present

    - name: Add Docker repository.
      get_url:
        url: "{{ install_docker_yum_repo_url }}"
        dest: '/etc/yum.repos.d/docker-ce.repo'
        owner: root
        group: root
        mode: 0644

    - name: Install Docker.
      package:
        name: docker-ce
        state: latest
      when: install_docker_package_check.rc != 0
      register: install_docker
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    when: ansible_os_family == 'RedHat'

  tags:
    - install-docker
